# Site settings
title: Qubes Issues
description: > # this means to ignore newlines until "baseurl:"
  This repository tracks issues and feature development progress for the Qubes
  OS Project.
# Project Settings
project_url: "https://www.qubes-os.org"
project_repo_path: "https://github.com/QubesOS"
project_repo_site: "/qubes-issues"
# Build settings
markdown: kramdown
highlighter: rouge
timezone: UTC
encoding: utf-8

